---
# Markdownlint configuration

# MD013 - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033 - Allow inline HTML (useful for badges, etc)
MD033: false

# MD041 - First line should be top-level heading
MD041: false
