---
- name: Backup Pompone Bot Data
  hosts: localhost
  connection: local

  vars_files:
    - ansible/group_vars/all.yml
    - ansible/group_vars/backup_ssh_keys.yml
    - ansible/host_vars/localhost/pompone.yml

  vars:
    bot_name: "Pompone"
    bot_dir: "bots/Pompone"
    backup_dir: "backups"
    backup_retention_days: 30
    timestamp: "{{ ansible_date_time.date }}"
    backup_filename: "pompone-backup-{{ timestamp }}.tar.gz"
    # Pompone-specific: add directories for pisg
    extra_backup_dirs:
      - archives
      - html
      - pisg-cache
      - pisg-config

  tasks:
    # Phase 1: Common backup preparation and base data
    - name: Execute common backup tasks
      ansible.builtin.include_tasks: ansible/tasks/backup-prepare.yml

    # Phase 2: Pompone-specific pisg data
    - name: Collect HTML output files (excluding README.md)
      ansible.builtin.find:
        paths: "{{ bot_dir }}/html"
        file_type: any
        recurse: true
        excludes:
          - README.md
      register: html_tree

    - name: Copy the HTML output tree
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ staging_dir.path }}/html/{{ item.path | regex_replace('^' ~ bot_dir ~ '/html/', '') }}"
        remote_src: true
        mode: preserve
      loop: "{{ html_tree.files }}"
      when: html_tree.matched > 0

    - name: Collect pisg-cache files (excluding README.md)
      ansible.builtin.find:
        paths: "{{ bot_dir }}/pisg-cache"
        file_type: any
        recurse: true
        excludes:
          - README.md
      register: pisg_cache_tree

    - name: Copy the pisg-cache tree
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ staging_dir.path }}/pisg-cache/{{ item.path | regex_replace('^' ~ bot_dir ~ '/pisg-cache/', '') }}"
        remote_src: true
        mode: preserve
      loop: "{{ pisg_cache_tree.files }}"
      when: pisg_cache_tree.matched > 0

    - name: Find pisg config customizations to backup
      ansible.builtin.find:
        paths: "{{ bot_dir }}/pisg-config"
        file_type: any
        excludes:
          - footer.txt
          - README.md
          - spam.cfg
          - user.cfg
      register: pisg_config_files

    - name: Copy pisg config customizations
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ staging_dir.path }}/pisg-config/{{ item.path | basename }}"
        remote_src: true
        mode: '0644'
      loop: "{{ pisg_config_files.files }}"
      when: pisg_config_files.matched > 0

    - name: Collect the log archives
      ansible.builtin.find:
        paths: "{{ bot_dir }}/archives"
        file_type: file
        pattern: "*.tar.gz"
        excludes:
          - README.md
      register: archives_files

    - name: Copy log archives
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ staging_dir.path }}/archives/{{ item.path | basename }}"
        remote_src: true
        mode: '0644'
      loop: "{{ archives_files.files }}"
      when: archives_files.matched > 0

    # Phase 3: Finalize backup
    - name: Finalize backup
      ansible.builtin.include_tasks: ansible/tasks/backup-finalize.yml
