---
- name: Deploy Pompone Eggdrop Bot
  hosts: localhost
  connection: local

  vars_files:
    - ansible/group_vars/all.yml
    - ansible/group_vars/backup_ssh_keys.yml
    - ansible/host_vars/localhost/pompone.yml

  tasks:

    # Phase 1: Common deploy preparation tasks and dependency resolution
    - name: Check for local overrides file
      ansible.builtin.stat:
        path: ansible/host_vars/localhost/overrides.yml
      register: overrides_stat

    - name: Load local override vars if present
      ansible.builtin.include_vars:
        file: ansible/host_vars/localhost/overrides.yml
      when: overrides_stat.stat.exists

    - name: Run common tasks
      ansible.builtin.import_tasks: ansible/tasks/deploy-prepare.yml

    # Phase 2: Pompone-specific tasks.
    - name: Generate pisg.cfg from template
      ansible.builtin.template:
        src: templates/pisg.cfg.j2
        dest: "bots/Pompone/pisg-config/pisg.cfg"
        mode: "0644"
      when: pisg_enabled | default(false)

    - name: Check for required pisg static config files
      ansible.builtin.stat:
        path: "bots/Pompone/pisg-config/{{ item }}"
      register: pisg_static_files
      loop:
        - user.cfg
        - spam.cfg
        - footer.txt
      when: pisg_enabled | default(false)

    - name: Warn about missing pisg config files
      ansible.builtin.debug:
        msg: "WARNING: {{ item.item }} not found. PISG may not work correctly."
      loop: "{{ pisg_static_files.results }}"
      when:
        - pisg_enabled | default(false)
        - not item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: Generate pisg footer from template
      ansible.builtin.template:
        src: templates/pisg-footer.txt.j2
        dest: "bots/Pompone/pisg-config/footer.txt"
        mode: "0644"
      when: pisg_enabled | default(false)

    - name: Create annual stats rotation cron job
      ansible.builtin.cron:
        name: "Annual stats rotation"
        user: "{{ ansible_user_id }}"
        job: >
          /usr/bin/env ansible-playbook
          {{ playbook_dir }}/rotate-pompone-pisg.yml
          >> {{ playbook_dir }}/bots/Pompone/logs/stats_rotation.log 2>&1
        minute: "30"
        hour: "0"
        day: "1"
        month: "1"
      when: pisg_enabled | default(false)

    - name: Extract IRC ports for firewall configuration
      ansible.builtin.set_fact:
        irc_ports: "{{ irc_servers | map(attribute='port') | map('regex_replace', '^\\+', '') | unique | sort | list }}"

    - name: Deploy Pompone with docker-compose
      community.docker.docker_compose_v2:
        project_src: bots/Pompone
        state: present

    - name: Build Pompone next steps message
      ansible.builtin.set_fact:
        pompone_next_steps: >-
          {{
            [
              "=" * 72,
              "Pompone deployment complete!",
              "=" * 72,
              "",
              "FIREWALL CONFIGURATION REQUIRED:",
              "-" * 33,
              "You must configure your firewall to allow the following:",
              "",
              "INBOUND:",
              "  - Port " ~ environment_variables.dcc_port ~
              " (DCC - botnet communication)"
            ]
            + (
              [
                "  - Port " ~ environment_variables.stats_port ~
                " (HTTP - PISG statistics)"
              ]
              if pisg_enabled | default(false) else []
            )
            + [
              "",
              "OUTBOUND:",
              "  - Ports " ~ (irc_ports | join(', ')) ~ " (IRC servers)",
              "  - Port 22 (SSH - for off-site backups)",
              "",
              "MANAGEMENT COMMANDS:",
              "-" * 20,
              "View logs:",
              "  cd bots/Pompone && docker compose logs -f",
              "",
              "Check status:",
              "  cd bots/Pompone && docker compose ps",
              "",
              "NEXT STEPS:",
              "-" * 11,
              "1. Configure firewall (see above)",
              "2. Link to botnet (see README.md for Post-deploy requirements)",
              "3. Test backup: ansible-playbook backup-pompone.yml",
              "",
              "=" * 72
            ]
          }}

    - name: Display next steps
      ansible.builtin.debug:
        msg: "{{ pompone_next_steps }}"

    # Phase 3: Finalize and validate deployment and present user feedback
    - name: Run finalize tasks
      ansible.builtin.import_tasks: ansible/tasks/deploy-finalize.yml
