---
- name: Deploy Pompone Eggdrop Bot
  hosts: localhost
  connection: local

  vars_files:
    - ansible/group_vars/all.yml
    - ansible/host_vars/localhost/pompone.yml
    - ansible/host_vars/localhost/overrides.yml

  tasks:

    - name: Run common tasks
      ansible.builtin.import_tasks: ansible/tasks/common.yml

    - name: Generate pisg.cfg from template
      ansible.builtin.template:
        src: templates/pisg.cfg.j2
        dest: "bots/Pompone/pisg-config/pisg.cfg"
        mode: "0644"
      become: true
      when: pisg_enabled | default(false)

    - name: Check for required pisg static config files
      ansible.builtin.stat:
        path: "bots/Pompone/pisg-config/{{ item }}"
      register: pisg_static_files
      loop:
        - user.cfg
        - spam.cfg
        - footer.txt
      when: pisg_enabled | default(false)

    - name: Warn about missing pisg config files
      ansible.builtin.debug:
        msg: "WARNING: {{ item.item }} not found. PISG may not work correctly."
      loop: "{{ pisg_static_files.results }}"
      when:
        - pisg_enabled | default(false)
        - not item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: Generate .env file with port configuration
      ansible.builtin.copy:
        content: |
          # Generated by Ansible - Do not edit manually
          # Source of truth: ansible/host_vars/localhost/pompone.yml

          {% for key, val in environment_variables.items() %}
          {{ key | upper }}={{ val }}
          {% endfor %}
        dest: "bots/Pompone/.env"
        mode: '0600'

    - name: Deploy Pompone with docker-compose
      community.docker.docker_compose_v2:
        project_src: bots/Pompone
        state: present

    - name: Display next steps
      ansible.builtin.debug:
        msg: |
          Pompone deployment complete!

          To view logs:
            docker compose -f bots/Pompone/docker-compose.yml logs -f

          To check status:
            docker compose -f bots/Pompone/docker-compose.yml ps

          To connect via telnet (if configured):
            telnet localhost 2020
