---
# SSH connection details for off-site backups
# Automatically populated during deployment
backup_ssh_public_keys:
  decisis:
    host: sea.loopstart.org
    path: /home/decisis/efnetmoto-fleet/backups
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII3gYV/gtpQF2Dg2wywgSL9COMt+ZUGCzT6X0InhI1c3
    user: decisis
  pompone:
    host: pompone.efnetmoto.com
    path: /home/tedski/src/efnetmoto-fleet/backups
    ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE21/qmdiKaPGT6KCjYLSapVkXaMx7BhpzkJIXkF7Zxz
    user: tedski
  xerokewl:
    host: ''
    path: ''
    ssh_public_key: ''
    user: ''
